# Generated by Django 5.0.2 on 2024-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0003_rename_is_prenuim_food_is_premium'),
        ('app_general', '0003_alter_subscription_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='food',
        ),
        migrations.AddField(
            model_name='subscription',
            name='food_set',
            field=models.ManyToManyField(to='app_food.food'),
        ),
    ]
