# Generated by Django 5.0.2 on 2024-02-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0002_food_description_food_special_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='is_prenuim',
            new_name='is_premium',
        ),
    ]
