# Generated by Django 5.0.2 on 2024-02-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0003_rename_is_prenuim_food_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_relative_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='promotion_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='special_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
